<?php
/**
 * WidgetTemplateApiTest
 * PHP version 5
 *
 * @category Class
 * @package  BigCommerce\Widgets
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Widgets
 *
 * Create and manage [widgets](/api-docs/storefront/widgets/widgets-overview), widget templates, regions, and placements.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.21
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace BigCommerce\Widgets;

use BigCommerce\Widgets\Configuration;
use BigCommerce\Widgets\ApiException;
use BigCommerce\Widgets\ObjectSerializer;

/**
 * WidgetTemplateApiTest Class Doc Comment
 *
 * @category Class
 * @package  BigCommerce\Widgets
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class WidgetTemplateApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createWidgetTemplate
     *
     * Create a Widget Template.
     *
     */
    public function testCreateWidgetTemplate()
    {
    }

    /**
     * Test case for deleteWidgetTemplate
     *
     * Delete A Widget Template.
     *
     */
    public function testDeleteWidgetTemplate()
    {
    }

    /**
     * Test case for getWidgetTemplate
     *
     * Get a Widget Template.
     *
     */
    public function testGetWidgetTemplate()
    {
    }

    /**
     * Test case for getWidgetTemplates
     *
     * Get All Widget Templates.
     *
     */
    public function testGetWidgetTemplates()
    {
    }

    /**
     * Test case for updateWidgetTemplate
     *
     * Update a Widget Template.
     *
     */
    public function testUpdateWidgetTemplate()
    {
    }
}
